"""initial schema

Revision ID: 8f9c4c57cbbf
Revises: 
Create Date: 2026-06-27 19:02:08.954710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9c4c57cbbf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('rol', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tel_emergencia', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profesores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jefe', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargo_de',
    sa.Column('profesor', sa.Integer(), nullable=False),
    sa.Column('alumno', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profesor'], ['profesores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('profesor', 'alumno')
    )
    op.create_table('detalles_alumno',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('imc', sa.Float(), nullable=True),
    sa.Column('grasa_corporal', sa.Float(), nullable=True),
    sa.Column('masa_muscular', sa.Float(), nullable=True),
    sa.Column('grasa_visceral', sa.Float(), nullable=True),
    sa.Column('edad_metabolica', sa.Float(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_evaluacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('semaforo', sa.Enum('ROJO', 'AMARILLO', 'VERDE', name='colorsemaforo'), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluaciones.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuestas_evaluacion')
    op.drop_table('evaluaciones')
    op.drop_table('detalles_alumno')
    op.drop_table('cargo_de')
    op.drop_table('profesores')
    op.drop_table('preguntas')
    op.drop_table('alumnos')
    op.drop_table('usuarios')
    op.drop_table('categorias')
    # ### end Alembic commands ###
