"""add apellido a profesores

Revision ID: a3f05e42006f
Revises: 0453fb292603
Create Date: 2026-07-18 02:02:43.120598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f05e42006f'
down_revision: Union[str, Sequence[str], None] = '0453fb292603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profesores', sa.Column('apellido', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profesores', 'apellido')
    # ### end Alembic commands ###
