"""add entrenamientos

Revision ID: f497471f388f
Revises: 8f9c4c57cbbf
Create Date: 2026-06-28 00:06:53.841325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f497471f388f'
down_revision: Union[str, Sequence[str], None] = '8f9c4c57cbbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrenamientos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alumno_id', sa.Uuid(), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('horario', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entrenamientos')
    # ### end Alembic commands ###
